"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/Users/haynesn/code/dotfiles/src/vim/repos/github.com/Shougo/dein.vim

" Required:
call dein#begin('/Users/haynesn/code/dotfiles/src/vim')

" Let dein manage dein
" Required:
call dein#add('Shougo/dein.vim')

" Add or remove your plugins here:
call dein#add('Shougo/neosnippet.vim')
call dein#add('Shougo/neosnippet-snippets')

" You can specify revision/branch/tag.
call dein#add('Shougo/vimshell', { 'rev': '3787e5' })

" Required:
call dein#end()

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
"if dein#check_install()
"  call dein#install()
"endif

"End dein Scripts-------------------------

" General
set number
set showcmd
set encoding=utf-8              "UTF8
set ls=2                        "Show status line
set expandtab                   "Spaces, no tabs
set backspace=2                 "Make backspacing work in insert
set tabstop=2                   "4 spaces per tab
set shiftwidth=2                "4 spaces for autoindent
set autoindent                  "Set new line to previous line indent
set autoread                    "Update files on change
set smartindent                 "Automatically indent
" set nobackup                    "No backups!
set visualbell                  "No sounds!
set noswapfile                  "No swaps!
set backupcopy=yes

" Syntax
syntax on
" colorscheme dracula

" Mappings
let mapleader = ","
inoremap jk <esc>

nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>ez :vsp ~/.zshrc<CR>
nnoremap <leader>sv :source $MYVIMRC<cr>

nnoremap B ^
nnoremap E $

map <Leader> <Plug>(easymotion-prefix)
