export WHOAMI=`whoami`
export BREW=`brew --prefix`

function safe_source() {
  [[ -f "$1" ]] && source "$1"
}

function source_env() {
  safe_source .env
}

autoload -U compinit compdef
autoload -U add-zsh-hook
autoload colors
compinit
colors

# Exports
export EDITOR="nvim"
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$PATH:`yarn global bin`"

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
export JAVA_HOME="/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home"

# Secrets
safe_source $PWD/.env

source $BREW/etc/profile.d/z.sh
source $HOME/.aliases
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
source $BREW/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh

add-zsh-hook chpwd source_env
source_env

bindkey -e
bindkey '^[[A'    history-substring-search-up
bindkey '^[[B'    history-substring-search-down
bindkey '^[[3~'   delete-char
bindkey '^[3;5~'  delete-char

eval "$(rbenv init -)"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
